Routes:
  schedule:
    class: ScheduleAPI
    id_field: week
  picks:
    class: PicksAPI
    id_field: week
  member:
    profile:
      class: ProfileAPI
      id_field: user_id
  gameday:
    class: GameDayAPI
    id_field: week
  results:
    class: ResultsAPI
    id_field: week
  trashtalk:
    class: TrashTalkAPI
    id_field: week